name: Node Continuous Integration

on:
  push:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: touch sample
      - run: echo aws_host="gowtham" >> sample
      - run: npm ci
      - run: npm audit
      - run: npm test
      - run: npm run build
