name: Node Continuous Integration

on:
  push:

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: tangro/actions-audit@v1.1.32
        with: post-comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - run: echo $GITHUB_CONTEXT
      - run: touch sample
      - run: echo "gowtham" >> sample
      - run: npm ci
      - run: npm audit || true
      - run: npm test
      - run: npm run build
